config = {
    "openmeteo_forecasts": {
        "partition_folder_name": "forecasts",
        "new_data_file_prefixes": ["multi_model_forecast - "],
        "start_date_field": "date",
        "record_index_fields": [
            "datetime",
            "forecast_temperature",
            "city",
            "model_timestamp",
            "model_name",
            "model_id",
            "date",
        ],
        "output_columns": [
            "datetime",
            "forecast_temperature",
            "model_timestamp",
            "current_timestamp",
            "model_name",
            "model_id",
            "date",
            "month",
            "year",
            "forecast_horizon",
            "forecast_horizon_hours",
            "is_model_timestamp_prior_day",
            "is_model_timestamp_same_day",
            "datetime_utc",
            "city",
            "year_month",
        ],
        "partition_columns": ["city", "year_month"],
    },
    "accuweather_forecasts": {
        "partition_folder_name": "accuweather",
        "new_data_file_prefixes": [
            "accuweather_12h_austin_",
            "accuweather_12h_chicago_",
            "accuweather_12h_denver_",
            "accuweather_12h_houston_",
            "accuweather_12h_los_angeles_",
            "accuweather_12h_miami_",
            "accuweather_12h_philadelphia_",
        ],
        "start_date_field": "date",
    },
    "nws_observations": {
        "partition_folder_name": "nws_observations",
        "new_data_file_prefixes": ...,
        "start_date_field": "date",
    },
    "candlesticks": {
        "partition_folder_name": "candlesticks",
        "new_data_file_prefixes": ...,
        "start_date_field": "date",
    },
}
