config = {
    "openmeteo_forecasts": {
        "dataset_name": "forecasts",
        "new_data_file_prefixes": ["multi_model_forecast - "],
        "new_data_file_suffixes": None,
        "start_date_field": "date",
        "start_date_format": "YYYY-MM-DD",
        "record_index_fields": [
            "datetime",
            "forecast_temperature",
            "city",
            "model_timestamp",
            "model_name",
            "model_id",
            "date",
        ],
        "output_columns": [
            "datetime",
            "forecast_temperature",
            "model_timestamp",
            "current_timestamp",
            "model_name",
            "model_id",
            "date",
            "month",
            "year",
            "forecast_horizon",
            "forecast_horizon_hours",
            "is_model_timestamp_prior_day",
            "is_model_timestamp_same_day",
            "datetime_utc",
            "city",
            "year_month",
        ],
        "partition_columns": ["city", "year_month"],
    },
    "accuweather_forecasts": {
        "dataset_name": "accuweather",
        "new_data_file_prefixes": [
            "accuweather_12h_austin_",
            "accuweather_12h_chicago_",
            "accuweather_12h_denver_",
            "accuweather_12h_houston_",
            "accuweather_12h_los_angeles_",
            "accuweather_12h_miami_",
            "accuweather_12h_philadelphia_",
        ],
        "new_data_file_suffixes": None,
        "start_date_field": "date",
        "start_date_format": "YYYYMMDD",
    },
    "nws_observations": {
        "dataset_name": "nws_observations",
        "new_data_file_prefixes": ...,
        "new_data_file_suffixes": None,
        "start_date_field": "date",
        "start_date_format": None,
        "record_index_fields": None,
        "output_columns": None,
        "partition_columns": None,
    },
    "candlesticks": {
        "dataset_name": "candlesticks",
        "new_data_file_prefixes": [
            "KXHIGHAUS-",
            "KXHIGHCHI-",
            "KXHIGHDEN-",
            "KXHIGHHOU-",
            "KXHIGHLAX-",
            "KXHIGHMIA-",
            "KXHIGHNY-",
            "KXHIGHPHIL-",
        ],
        "new_data_file_suffixes": ["_candlesticks"],
        "start_date_field": "date",
        "start_date_format": "YYMMMDD",
        "record_index_fields": None,
        "output_columns": None,
        "partition_columns": None,
    },
}
